# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-5
  region: eu-central-1 

iam:
  withOIDC: true

karpenter:
  version: 'v0.31.0' # Exact version must be provided
  createServiceAccount: true # default is false
  withSpotInterruptionQueue: true # adds all required policies and rules for supporting Spot Interruption Queue, default is false

managedNodeGroups:
  - name: ng-1
    instanceType: m5.large 
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
