apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nxhop
  source:
    path: k8s/argo-workflows/overlays/production
    repoURL: https://github.com/nxhop/portal_aws_infrustructure 
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

