apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nxhop 
  source:
    path: k8s/cert-manager
    repoURL: https://github.com/nxhop/portal_aws_infrustructure
    targetRevision: HEAD
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
