apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nxhop 
  source:
    path: k8s/nginx-ingress
    repoURL: https://github.com/agud97/eks-karpenter 
    targetRevision: HEAD
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
