apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nxhop 
  source:
    path: k8s/sealedsecrets
    repoURL: https://github.com/agud97/eks-karpenter 
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
