---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-sa-ops

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-events-role
subjects:
- kind: ServiceAccount
  name: events-sa-ops
  namespace: argo-events
---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ops-events-role
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*" 
    resources:
      - workflows
      - workflows/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
      - sensors
      - sensors/finalizers
      - sensors/status
      - eventsources
      - eventsources/finalizers
      - eventsources/status
      - eventbus
      - eventbus/finalizers
      - eventbus/status
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - configmaps
      - secrets
      - services
      - persistentvolumeclaims
      - pods/log
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update   

---

